Fal 13
willpennell/falcon-amazon-java-login pull request #4
Opened 2023-05-20 18:18 UTC by willpennell

Login API working, unit tested, custom Repository code test and integration tested with DB, end-to-end with manual Postman  testing.

2023-05-20 19:56 UTC, VincentFleetwood requested changes

2023-05-20 19:56 UTC, VincentFleetwood commented on login/src/test/java/com/teamfalcon/login/service/LoginServiceTest.java
> +        assertEquals(expectedSuccess, actualResponse.getSuccess());
assertTrue

2023-05-20 19:56 UTC, VincentFleetwood commented on login/src/test/java/com/teamfalcon/login/service/LoginServiceTest.java
> +        assertEquals(returnedUserToken.getToken(), actualResponse.getToken());
try and assert a value not the result of a getter please

2023-05-20 19:56 UTC, VincentFleetwood commented on login/src/test/java/com/teamfalcon/login/testmodels/TestUserEntityFactory.java
> +public class TestUserEntityFactory {
these classes are often called Fixtures in test code

2023-05-21 16:35 UTC, willpennell commented on login/src/main/java/com/teamfalcon/login/exceptions/ExceptionMessages.java
> +package com.teamfalcon.login.exceptions;
perfect, will do!

2023-05-21 16:35 UTC, willpennell commented on login/src/main/java/com/teamfalcon/login/service/LoginServiceImpl.java
> +            throw new EntityNotFoundException(ENTITY_NOT_FOUND_ERROR_MESSAGE);
OK great!

2023-05-21 16:36 UTC, willpennell commented on login/src/main/java/com/teamfalcon/login/model/UserEntity.java
> +    private Boolean isDeleted;
sure!

2023-05-23 14:44 UTC, Jomm0 commented
All looks good to me; can't see anything additional which hasn't already been covered by Vince, which have now been sorted.

2023-05-23 14:47 UTC, Jomm0 approved these changes
All changes requested have been implemented.

2023-05-23 16:07 UTC, VincentFleetwood approved these changes

2023-05-23 16:07 UTC, merged